[package]
name = "typenotion"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
codegen = "0.2"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0.200", features = ["derive"] }
